# Generated by Django 5.2.3 on 2025-07-03 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
    ]
