# Generated by Django 5.0.6 on 2024-08-13 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 8, 13, 14, 44, 3, 346442), verbose_name='дата создания'),
        ),
    ]
