# Generated by Django 5.0.6 on 2024-08-13 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 8, 13, 14, 45, 23, 903929, tzinfo=datetime.timezone.utc), verbose_name='дата создания'),
        ),
    ]
