# Generated by Django 5.0.6 on 2025-06-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('phone', models.CharField(max_length=10, verbose_name='телефон')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'обратная связь',
                'verbose_name_plural': 'обратные связи',
            },
        ),
    ]
