# Generated by Django 5.2.3 on 2025-09-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='flag',
            field=models.BooleanField(verbose_name='признак'),
        ),
        migrations.AlterField(
            model_name='version',
            name='number',
            field=models.FloatField(verbose_name='номер'),
        ),
    ]
